### ISSUE TITLE
Error messages when generating dataset

### ISSUE THREAD

**Issue by zunction** [husheng12345/SRAN#1]
Hi,

I am trying to generate the dataset based on the instructions to run the `main.py` file. However, it returns various error messages like 

```
 0%|                                                    | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "I-RAVEN/main.py", line 254, in <module>
    main()
  File "I-RAVEN/main.py", line 250, in main
    separate(args, all_configs)
  File "I-RAVEN/main.py", line 139, in separate
    pos = [i for i in xrange(len(selected_attr)) if selected_attr[i][1]=='Number']
NameError: name 'xrange' is not defined
```
which I replaced `xrange` with `range` only to get another error

```
 0%|                                                    | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "I-RAVEN/main.py", line 254, in <module>
    main()
  File "I-RAVEN/main.py", line 250, in main
    separate(args, all_configs)
  File "I-RAVEN/main.py", line 212, in separate
    dom = dom_problem(context + candidates, rule_groups)
  File "/home/users/zhangsheng_lai/SRAN/I-RAVEN/serialize.py", line 106, in dom_problem
    entity_l.set("mask", rle_encode(get_mask(entity_bbox, entity_type, entity_size, entity_angle)))
  File "/home/users/zhangsheng_lai/SRAN/I-RAVEN/api.py", line 88, in rle_encode
    runs[1::2] -= runs[::2]
ValueError: operands could not be broadcast together with shapes (225,) (226,) (225,) 
```

For reference, this is the environment which I'm working in:

```
Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
ca-certificates           2021.10.26           h06a4308_2  
certifi                   2021.10.8        py37h06a4308_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgomp                   9.3.0               h5101ec6_17  
libstdcxx-ng              9.3.0               hd4cf53a_17  
ncurses                   6.3                  h7f8727e_2  
numpy                     1.16.6                   pypi_0    pypi
opencv-python             4.2.0.32                 pypi_0    pypi
openssl                   1.1.1l               h7f8727e_0  
pillow                    6.2.2                    pypi_0    pypi
pip                       21.0.1           py37h06a4308_0  
python                    3.7.11               h12debd9_0  
readline                  8.1                  h27cfd23_0  
scipy                     1.2.3                    pypi_0    pypi
setuptools                58.0.4           py37h06a4308_0  
sqlite                    3.36.0               hc218d9a_0  
tk                        8.6.11               h1ccaba5_0  
tqdm                      4.54.1                   pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_1  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3 
```

Am I doing it wrongly? And could I get help to generate the dataset successfully?

Thanks

**Comment by zunction** [comment]
Realised that the code is written in Python 2.7. When run on Python 2.7 those issues do not occur.
